const palette = {
  charcoal: '#1a1a1a',
  charcoalMid: '#242424',
  charcoalLight: '#2e2e2e',
  surface: '#1f1f1f',
  border: '#333333',
  borderLight: '#3a3a3a',

  white: '#ffffff',
  offWhite: '#f5f5f0',
  textPrimary: '#f0f0ec',
  textSecondary: '#9a9a96',
  textMuted: '#666660',

  accent: '#e8e0d0',
  accentDim: '#b0a898',
  red: '#e05555',
  redDim: '#c04444',
  green: '#6ab187',
  greenDim: '#4d8f67',

  lightBg: '#f5f5f0',
  lightSurface: '#ffffff',
  lightSurface2: '#f0f0eb',
  lightBorder: '#deded8',
  lightText: '#1a1a1a',
  lightTextSecondary: '#666660',
  lightTextMuted: '#aaa9a4',
};

export default {
  light: {
    background: palette.lightBg,
    surface: palette.lightSurface,
    surface2: palette.lightSurface2,
    border: palette.lightBorder,
    text: palette.lightText,
    textSecondary: palette.lightTextSecondary,
    textMuted: palette.lightTextMuted,
    accent: '#5a5245',
    accentDim: '#8a7f72',
    red: palette.red,
    green: palette.green,
    tint: '#5a5245',
    tabIconDefault: palette.lightTextMuted,
    tabIconSelected: '#5a5245',
  },
  dark: {
    background: palette.charcoal,
    surface: palette.charcoalMid,
    surface2: palette.charcoalLight,
    border: palette.border,
    text: palette.textPrimary,
    textSecondary: palette.textSecondary,
    textMuted: palette.textMuted,
    accent: palette.accent,
    accentDim: palette.accentDim,
    red: palette.red,
    green: palette.green,
    tint: palette.accent,
    tabIconDefault: palette.textMuted,
    tabIconSelected: palette.accent,
  },
};
